window.ISSUES_DATA = {
  "generatedAt": "2026-05-19 14:22",
  "source": "Issues Register.xlsx",
  "issues": [
    {
      "id": "ID-01",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "",
      "journeyStage": "Payment processing",
      "title": "Understand how off-system BSBs are being used",
      "problemScenario": "In the current Payday Super ecosystem, there is limited visibility and understanding of how off-system BSBs are being used across payment flows. This creates uncertainty around how payments are routed, the availability of alternatives, and the potential impact on AP+ products and services. Currently, the use of off-system BSBs is not well documented or consistently understood across participants. There is a need to conduct a structured analysis of off-system BSB usage, associated challenges, and viable alternatives to inform product and ecosystem decisions.",
      "issueType": "Gap",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Accounts",
      "productsImpacted": "CoP",
      "owner": "Nick",
      "priority": "MEDIUM",
      "horizon": "LONG",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "Decisions pending.",
      "notes": "",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "Accounts",
      "products": [
        "Accounts",
        "CoP"
      ]
    },
    {
      "id": "ID-02",
      "mainUseCase": "Super",
      "useCasesImpacted": "Government",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "",
      "journeyStage": "Set up & Account",
      "title": "Super fund contribution accounts not NPP-enabled or aligned with FVS Account reachability for Businesses accounts (Osko)",
      "problemScenario": "In the Payday Super ecosystem, some super funds do not have their nominated contribution bank accounts enabled to receive NPP payments or correctly registered in the ATO Fund Validation Service (FVS). This results in funds being unable to receive employer contributions via NPP, creating a critical gap in payment processing and preventing contributions from being received and allocated. Currently, inconsistencies exist where accounts are either not enabled for NPP, rely on legacy or off-system BSB structures, or are not updated in the FVS despite being enabled. With regulatory requirements mandating NPP contribution capability by July 2026, there is a need for super funds to ensure their contribution accounts are NPP-enabled and accurately maintained in the FVS, including enabling existing accounts, repurposing suitable accounts, or establishing new compliant accounts where required.",
      "issueType": "Opportunity",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Accounts",
      "productsImpacted": "Osko",
      "owner": "Nick",
      "priority": "MEDIUM",
      "horizon": "LONG",
      "status": "WIP",
      "currentAction": "Ensure contribution accounts are NPP-enabled and accurately maintained.",
      "decisionNeeded": "",
      "notes": "Readiness: Account Reach data to come in end of March",
      "link1": "NPP Bank account enablement - Troubleshooting - Move to NPP (MTN) Program Squad - Confluence",
      "link2": "",
      "lastUpdated": "2026-05-04",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Government"
      ],
      "product": "Accounts",
      "products": [
        "Accounts",
        "Osko"
      ]
    },
    {
      "id": "ID-03",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "",
      "journeyStage": "",
      "title": "BSB redirection creates risks for payments where account details do not change often.",
      "problemScenario": "In the Payday Super ecosystem, BSB redirection can occur in payment flows where account details do not change frequently, such as pension-related payments. This creates a risk that payments may be routed differently than expected, reducing transparency and potentially impacting payment reliability and reconciliation. Currently, BSB redirection behaviour is not always visible or well understood by participants, particularly in legacy or off-system account structures. There is a need to better understand the implications of BSB redirection and assess potential solutions to improve transparency, control and reliability of payment routing.",
      "issueType": "Risk",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Accounts",
      "productsImpacted": "PayID",
      "owner": "Nick",
      "priority": "HIGH",
      "horizon": "MEDIUM",
      "status": "WIP",
      "currentAction": "Better understand the implications of BSB redirection and assess potential solutions to improve transparency, control and reliability of payment routing.",
      "decisionNeeded": "",
      "notes": "Analysis on possible solutions are being undertaken",
      "link1": "To be created",
      "link2": "",
      "lastUpdated": "2026-05-04",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "Accounts",
      "products": [
        "Accounts",
        "PayID"
      ]
    },
    {
      "id": "ID-04",
      "mainUseCase": "Super",
      "useCasesImpacted": "All",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "",
      "journeyStage": "Receiving, validating, and reconciling (Employee's Super Fund)",
      "title": "Readiness of super funds to receive NPP payments by 1 July",
      "problemScenario": "",
      "issueType": "Product Idea",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Accounts",
      "productsImpacted": "PayTo",
      "owner": "Bianca",
      "priority": "HIGH",
      "horizon": "SHORT",
      "status": "WIP",
      "currentAction": "Follow up with super funds to assess readiness.",
      "decisionNeeded": "",
      "notes": "Enablement: Tracking of SF readiness",
      "link1": "NPP Bank account enablement - Troubleshooting - Move to NPP (MTN) Program Squad - Confluence",
      "link2": "OLD - Participant engagement with Super Funds Dec2025.xlsx",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "All"
      ],
      "product": "Accounts",
      "products": [
        "Accounts",
        "PayTo"
      ]
    },
    {
      "id": "ID-05",
      "mainUseCase": "Super",
      "useCasesImpacted": "Business Payments",
      "category": "Data Quality & Validation",
      "category2": "",
      "journeyStage": "Set up & Account",
      "title": "COP is the match outcome only enough information or is there more information that could be provided?",
      "problemScenario": "",
      "issueType": "PE",
      "dependencies": "ID-06",
      "relatedInitiative": "",
      "primaryProduct": "CoP",
      "productsImpacted": "SCT",
      "owner": "Tina",
      "priority": "MEDIUM",
      "horizon": "MEDIUM",
      "status": "WIP",
      "currentAction": "CoP being assessed for Payday Super",
      "decisionNeeded": "Decisions pending.",
      "notes": "External privacy advice currently underway with June PRC paper planned to address Use Case N12.5.3b expansion",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Business Payments"
      ],
      "product": "CoP",
      "products": [
        "CoP",
        "SCT"
      ]
    },
    {
      "id": "ID-06",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Data Quality & Validation",
      "category2": "",
      "journeyStage": "Preparation and data creation",
      "title": "Using COP at the time of onboarding the entity you're paying to",
      "problemScenario": "",
      "issueType": "Dependency",
      "dependencies": "ID-05",
      "relatedInitiative": "",
      "primaryProduct": "CoP",
      "productsImpacted": "Reporting",
      "owner": "Tina",
      "priority": "TBD",
      "horizon": "TBD",
      "status": "ACKNOWLEDGE",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "Already part of the discussions with DSPs and providers",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "CoP",
      "products": [
        "CoP",
        "Reporting"
      ]
    },
    {
      "id": "ID-07",
      "mainUseCase": "Super",
      "useCasesImpacted": "Government",
      "category": "",
      "category2": "",
      "journeyStage": "",
      "title": "AP+ to be clearing house",
      "problemScenario": "",
      "issueType": "Gap",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Other",
      "productsImpacted": "Other",
      "owner": "TBD",
      "priority": "TBD",
      "horizon": "TBD",
      "status": "ACKNOWLEDGE",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "This may not align with AP+ strategic goals",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Government"
      ],
      "product": "Other",
      "products": [
        "Other"
      ]
    },
    {
      "id": "ID-08",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "",
      "journeyStage": "Preparation and data creation",
      "title": "Sequencing of payments that affect a business cashflow (e.g. credits occur before debits)",
      "problemScenario": "",
      "issueType": "Opportunity",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Other",
      "productsImpacted": "Accounts",
      "owner": "Bianca",
      "priority": "MEDIUM",
      "horizon": "MEDIUM",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "Create general awareness of the impacts of cash flow management (Base deck/FAQs/Implementation Guide)",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "Other",
      "products": [
        "Other",
        "Accounts"
      ]
    },
    {
      "id": "ID-09",
      "mainUseCase": "Super",
      "useCasesImpacted": "All",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "",
      "journeyStage": "",
      "title": "Understanding the to-be state and the process flows sequencing as result and pre-requistes.",
      "problemScenario": "",
      "issueType": "Risk",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Other",
      "productsImpacted": "CATSCT",
      "owner": "Bianca",
      "priority": "MEDIUM",
      "horizon": "SHORT",
      "status": "WIP",
      "currentAction": "",
      "decisionNeeded": "Decisions pending.",
      "notes": "To be state has been considered but not documented",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "All"
      ],
      "product": "Other",
      "products": [
        "Other",
        "CATSCT"
      ]
    },
    {
      "id": "ID-10",
      "mainUseCase": "Super",
      "useCasesImpacted": "Business Payments",
      "category": "Exceptions, Returns & Error Handling",
      "category2": "Ecosystem Readiness & External Constraints",
      "journeyStage": "Investigation and returns (unhappy path)",
      "title": "Understanding the unsolicited payment return process and whether it is fit for purpose for businesses",
      "problemScenario": "",
      "issueType": "Product Idea",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Other",
      "productsImpacted": "CoP",
      "owner": "Bianca",
      "priority": "HIGH",
      "horizon": "SHORT",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "Next Step: Understanding what are current offerings",
      "link1": "To be created",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Business Payments"
      ],
      "product": "Other",
      "products": [
        "Other",
        "CoP"
      ]
    },
    {
      "id": "ID-11",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "",
      "journeyStage": "",
      "title": "Increase in transaction volumes for super contributions as a result of changes in processing.",
      "problemScenario": "",
      "issueType": "PE",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Other",
      "productsImpacted": "Osko",
      "owner": "Bianca",
      "priority": "HIGH",
      "horizon": "SHORT",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "Next Step: Education of the ecosystem (Base deck/FAQs)",
      "link1": "To be created",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "Other",
      "products": [
        "Other",
        "Osko"
      ]
    },
    {
      "id": "ID-12",
      "mainUseCase": "Super",
      "useCasesImpacted": "Government",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "",
      "journeyStage": "Receiving, validating, and reconciling (SuperStream)",
      "title": "Readiness of Clearing Houses to accept and send NPP payments",
      "problemScenario": "",
      "issueType": "Dependency",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Other",
      "productsImpacted": "PayID",
      "owner": "Bianca",
      "priority": "HIGH",
      "horizon": "MEDIUM",
      "status": "WIP",
      "currentAction": "Clearing house assessment against receive and send NPP payments",
      "decisionNeeded": "",
      "notes": "Enablement: Tracking of CH readiness. Pilots are underway",
      "link1": "To be created",
      "link2": "PRN reporting and Enablers analysis and tracking.xlsx",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Government"
      ],
      "product": "Other",
      "products": [
        "Other",
        "PayID"
      ]
    },
    {
      "id": "ID-13",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "",
      "journeyStage": "Payment processing",
      "title": "There are bank product differences that are outside our visibility or rules which impacts the customer experience and operations",
      "problemScenario": "Across the ecosystem, banks offer different product capabilities, rules and behaviours that are outside of AP+ visibility and control. This leads to inconsistencies in how payments are processed and experienced by customers. Currently, these differences result in operational complexity and fragmented user journeys. There is a need to align on minimum standards and expected behaviours across banks to provide a more consistent and predictable experience.",
      "issueType": "Gap",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Other",
      "productsImpacted": "PayTo",
      "owner": "Bianca",
      "priority": "MEDIUM",
      "horizon": "MEDIUM",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "Next Steps: Understanding some of the product differences when understanding the use cases",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "Other",
      "products": [
        "Other",
        "PayTo"
      ]
    },
    {
      "id": "ID-14",
      "mainUseCase": "Super",
      "useCasesImpacted": "All",
      "category": "Reconciliation, Reporting & Traceability",
      "category2": "Addressing Model (PayID & Account Structure)",
      "journeyStage": "Receiving, validating, and reconciling (SuperStream)",
      "title": "PayID not being available in the account statement reporting (EOD/Intraday)",
      "problemScenario": "",
      "issueType": "Opportunity",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Other",
      "productsImpacted": "SCT",
      "owner": "Ronita",
      "priority": "HIGH",
      "horizon": "MEDIUM",
      "status": "WIP",
      "currentAction": "Assessing account statement report",
      "decisionNeeded": "",
      "notes": "Enablement: Is doing analysis of what reporting is available for PayID and PayTo Next steps: Discussions with Participants",
      "link1": "PayID Reconciliation on bank statements - Move to NPP (MTN) Program Squad - Confluence",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "All"
      ],
      "product": "Other",
      "products": [
        "Other",
        "SCT"
      ]
    },
    {
      "id": "ID-15",
      "mainUseCase": "Super",
      "useCasesImpacted": "Business Payments",
      "category": "Payment instruction and Operation",
      "category2": "",
      "journeyStage": "Preparation and data creation",
      "title": "PayID aren't included in the payment instruction",
      "problemScenario": "",
      "issueType": "Risk",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayID",
      "productsImpacted": "Reporting",
      "owner": "Ronita",
      "priority": "HIGH",
      "horizon": "MEDIUM",
      "status": "WIP",
      "currentAction": "Piloting PayID field for payment instruction.",
      "decisionNeeded": "Decisions pending.",
      "notes": "Enablement: Is doing analysis of what reporting is available for PayID and PayTo",
      "link1": "PayID - Payment Instruction - Move to NPP (MTN) Program Squad - Confluence",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Business Payments"
      ],
      "product": "PayID",
      "products": [
        "PayID",
        "Reporting"
      ]
    },
    {
      "id": "ID-16",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Payment instruction and Operation",
      "category2": "",
      "journeyStage": "Set up & Account",
      "title": "DSP adoption of PayID - being able to store and send a payment instruction with a PayID",
      "problemScenario": "",
      "issueType": "Product Idea",
      "dependencies": "ID-19; ID-23; ID-24; ID-27",
      "relatedInitiative": "",
      "primaryProduct": "PayID",
      "productsImpacted": "Other",
      "owner": "Bianca",
      "priority": "HIGH",
      "horizon": "MEDIUM",
      "status": "WIP",
      "currentAction": "Assessing DSP feasibility",
      "decisionNeeded": "Decisions pending.",
      "notes": "Enablement: Working with DSPANZ, SAP, Xero on their implementation. Trying to get traction with Oracle Payroll providers will be targetted next",
      "link1": "Minimal coverage from the banks to pay to a PayID outside of an IB channel - Move to NPP (MTN) Program Squad - Confluence",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "PayID",
      "products": [
        "PayID",
        "Other"
      ]
    },
    {
      "id": "ID-17",
      "mainUseCase": "Super",
      "useCasesImpacted": "Government",
      "category": "Addressing Model (PayID & Account Structure)",
      "category2": "",
      "journeyStage": "Contribution data &payment method definition",
      "title": "Risk associated with the Payer/employer cannot pay to a PayID in their DSP, they will be entering the details into an online banking channel and get the appropriate authorisation",
      "problemScenario": "",
      "issueType": "PE",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayID",
      "productsImpacted": "Accounts",
      "owner": "Bianca",
      "priority": "HIGH",
      "horizon": "SHORT",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "Enablement: Working with DSPs to include PayID and understand existing reporting for reconciliation Next Steps: Education of employers and understanding the impacts (FAQs)",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Government"
      ],
      "product": "PayID",
      "products": [
        "PayID",
        "Accounts"
      ]
    },
    {
      "id": "ID-18",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "Addressing Model (PayID & Account Structure)",
      "journeyStage": "",
      "title": "Need to understand the process of registration of ABN PayIDs",
      "problemScenario": "In the onboarding and setup process, the registration and management of ABN-linked PayIDs is not clearly understood across participants. This creates friction in adoption and delays implementation of PayID-based solutions. Currently, there is inconsistent knowledge and no standardised approach to registering and managing ABN PayIDs. There is a need to define and document a clear, standardised registration process to support broader adoption.",
      "issueType": "Dependency",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayID",
      "productsImpacted": "CATSCT",
      "owner": "Ronita",
      "priority": "MEDIUM",
      "horizon": "SHORT",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "PayID",
      "products": [
        "PayID",
        "CATSCT"
      ]
    },
    {
      "id": "ID-19",
      "mainUseCase": "Super",
      "useCasesImpacted": "All",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "Addressing Model (PayID & Account Structure)",
      "journeyStage": "Contribution data &payment method definition",
      "title": "Understanding the PayID limits that have been implemented by banks",
      "problemScenario": "",
      "issueType": "Gap",
      "dependencies": "ID-16; ID-23; ID-24; ID-27",
      "relatedInitiative": "",
      "primaryProduct": "PayID",
      "productsImpacted": "CoP",
      "owner": "Ronita",
      "priority": "HIGH",
      "horizon": "SHORT",
      "status": "WIP",
      "currentAction": "Makes reports action-oriented instead of note-oriented",
      "decisionNeeded": "",
      "notes": "Creating the Capability Matrix and collecting the information",
      "link1": "Payments via PayID Limits - Move to NPP (MTN) Program Squad - Confluence",
      "link2": "Member Capability Matrix _PayID only.xlsx",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "All"
      ],
      "product": "PayID",
      "products": [
        "PayID",
        "CoP"
      ]
    },
    {
      "id": "ID-20",
      "mainUseCase": "Super",
      "useCasesImpacted": "Business Payments",
      "category": "Addressing Model (PayID & Account Structure)",
      "category2": "",
      "journeyStage": "Preparation and data creation",
      "title": "Bulk PayID Resolution (initiation, registration)",
      "problemScenario": "",
      "issueType": "Opportunity",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayID",
      "productsImpacted": "Osko",
      "owner": "Ronita",
      "priority": "MEDIUM",
      "horizon": "LONG",
      "status": "HOLD / BLOCKED",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "PE raised: i.110",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Business Payments"
      ],
      "product": "PayID",
      "products": [
        "PayID",
        "Osko"
      ]
    },
    {
      "id": "ID-21",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Addressing Model (PayID & Account Structure)",
      "category2": "",
      "journeyStage": "Receiving, validating, and reconciling (Employee's Super Fund)",
      "title": "PayID receivables implementation proliferation without any AP+ governance",
      "problemScenario": "",
      "issueType": "Risk",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayID",
      "productsImpacted": "PayID",
      "owner": "Ronita",
      "priority": "MEDIUM",
      "horizon": "LONG",
      "status": "HOLD / BLOCKED",
      "currentAction": "",
      "decisionNeeded": "Decisions pending.",
      "notes": "",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "PayID",
      "products": [
        "PayID"
      ]
    },
    {
      "id": "ID-22",
      "mainUseCase": "Super",
      "useCasesImpacted": "Government",
      "category": "Addressing Model (PayID & Account Structure)",
      "category2": "Exceptions, Returns & Error Handling",
      "journeyStage": "Preparation and data creation",
      "title": "PayID dedicated to Super Refunds",
      "problemScenario": "",
      "issueType": "Product Idea",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayID",
      "productsImpacted": "PayTo",
      "owner": "Bianca",
      "priority": "LOW",
      "horizon": "SHORT",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "Decisions pending.",
      "notes": "Education to the super funds/employers (FAQs). This has been included in the Super Implementation Guide",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Government"
      ],
      "product": "PayID",
      "products": [
        "PayID",
        "PayTo"
      ]
    },
    {
      "id": "ID-23",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "Addressing Model (PayID & Account Structure)",
      "journeyStage": "Set up & Account",
      "title": "Not all members support all types of PayID",
      "problemScenario": "In the current ecosystem, PayID is not a mandatory capability and is not consistently supported across participants, including differences in supported PayID types. This results in a fragmented experience and limits the scalability of PayID-based solutions. Currently, adoption and implementation vary significantly across banks and providers. There is a need to define a clear strategic direction for PayID adoption, including whether it should be mandated or incentivised.",
      "issueType": "PE",
      "dependencies": "ID-16; ID-19; ID-23; ID-27",
      "relatedInitiative": "",
      "primaryProduct": "PayID",
      "productsImpacted": "SCT",
      "owner": "Ronita",
      "priority": "MEDIUM",
      "horizon": "MEDIUM",
      "status": "WIP",
      "currentAction": "Makes reports action-oriented instead of note-oriented",
      "decisionNeeded": "Decisions pending.",
      "notes": "Creating the Capability Matrix and collecting the information",
      "link1": "",
      "link2": "Member Capability Matrix _PayID only.xlsx",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "PayID",
      "products": [
        "PayID",
        "SCT"
      ]
    },
    {
      "id": "ID-24",
      "mainUseCase": "Super",
      "useCasesImpacted": "All",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "",
      "journeyStage": "Set up & Account",
      "title": "PayID is NOT a mandatory product to be implemented",
      "problemScenario": "",
      "issueType": "Dependency",
      "dependencies": "ID-16; ID-19; ID-24; ID-27",
      "relatedInitiative": "",
      "primaryProduct": "PayID",
      "productsImpacted": "Reporting",
      "owner": "Ronita",
      "priority": "MEDIUM",
      "horizon": "LONG",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "",
      "link1": "Payments to PayID availability - Move to NPP (MTN) Program Squad - Confluence",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "All"
      ],
      "product": "PayID",
      "products": [
        "PayID",
        "Reporting"
      ]
    },
    {
      "id": "ID-25",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Data Quality & Validation",
      "category2": "Exceptions, Returns & Error Handling",
      "journeyStage": "Preparation and data creation",
      "title": "Additional PayID lookups (i.i68) decoupling from payment request / payment initiation / mandate creation. Needs to consider who in the value chain is able to utilise this. Consideration of the Alias name display beyond the banks",
      "problemScenario": "",
      "issueType": "Gap",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayID",
      "productsImpacted": "Other",
      "owner": "Ronita",
      "priority": "MEDIUM",
      "horizon": "LONG",
      "status": "WIP",
      "currentAction": "Makes reports action-oriented instead of note-oriented",
      "decisionNeeded": "",
      "notes": "Paper is being taken up to PRC",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "PayID",
      "products": [
        "PayID",
        "Other"
      ]
    },
    {
      "id": "ID-26",
      "mainUseCase": "Super",
      "useCasesImpacted": "Government",
      "category": "Addressing Model (PayID & Account Structure)",
      "category2": "",
      "journeyStage": "Contribution data &payment method definition",
      "title": "Considerations for the performance of Addressing Service given the uptake of PayID receivables and the potential volume of PayID resolution",
      "problemScenario": "",
      "issueType": "Opportunity",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayID",
      "productsImpacted": "Accounts",
      "owner": "Ronita",
      "priority": "MEDIUM",
      "horizon": "LONG",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Government"
      ],
      "product": "PayID",
      "products": [
        "PayID",
        "Accounts"
      ]
    },
    {
      "id": "ID-27",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Payment instruction and Operation",
      "category2": "",
      "journeyStage": "Contribution data &payment method definition",
      "title": "Limits on PayIDs payments within a payment instruction. This could be due to enumeration controls or throughput.",
      "problemScenario": "",
      "issueType": "Risk",
      "dependencies": "ID-16; ID-19; ID-23; ID-24",
      "relatedInitiative": "",
      "primaryProduct": "PayID",
      "productsImpacted": "CATSCT",
      "owner": "Ronita",
      "priority": "MEDIUM",
      "horizon": "MEDIUM",
      "status": "WIP",
      "currentAction": "Makes reports action-oriented instead of note-oriented",
      "decisionNeeded": "Decisions pending.",
      "notes": "Creating the Capability Matrix and collecting the information to understand existing limits",
      "link1": "",
      "link2": "Member Capability Matrix _PayID only.xlsx",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "PayID",
      "products": [
        "PayID",
        "CATSCT"
      ]
    },
    {
      "id": "ID-28",
      "mainUseCase": "Super",
      "useCasesImpacted": "All",
      "category": "Addressing Model (PayID & Account Structure)",
      "category2": "",
      "journeyStage": "Preparation and data creation",
      "title": "If PayID, someone needs to retain / maintain PayIDs. How well are Banks maintaining the currency of PayIDs? What is the extra work a business needs to undertake (e.g. if they issue one for each member, they need to ensure they deregister if the member leaves)?",
      "problemScenario": "",
      "issueType": "Product Idea",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayID",
      "productsImpacted": "CoP",
      "owner": "Ronita",
      "priority": "MEDIUM",
      "horizon": "MEDIUM",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "Decisions pending.",
      "notes": "Next Step: Understand the business processes that may be required. Do we need to look at the maintaince of banks?",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "All"
      ],
      "product": "PayID",
      "products": [
        "PayID",
        "CoP"
      ]
    },
    {
      "id": "ID-29",
      "mainUseCase": "Super",
      "useCasesImpacted": "Business Payments",
      "category": "Data Quality & Validation",
      "category2": "",
      "journeyStage": "Receiving, validating, and reconciling (Employee's Super Fund)",
      "title": "PayID Receivables could be an alternative to PRN",
      "problemScenario": "",
      "issueType": "PE",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayID",
      "productsImpacted": "Osko",
      "owner": "Bianca",
      "priority": "LOW",
      "horizon": "LONG",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Business Payments"
      ],
      "product": "PayID",
      "products": [
        "PayID",
        "Osko"
      ]
    },
    {
      "id": "ID-30",
      "mainUseCase": "Super",
      "useCasesImpacted": "Business Payments",
      "category": "Addressing Model (PayID & Account Structure)",
      "category2": "",
      "journeyStage": "Set up & Account",
      "title": "New PayID type - Super-specific PayID USI; it could be easier to mandate the use of a specific Super PayID",
      "problemScenario": "",
      "issueType": "Dependency",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayID",
      "productsImpacted": "PayID",
      "owner": "Ronita",
      "priority": "LOW",
      "horizon": "LONG",
      "status": "BACKLOG",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "Enablement backlog",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Business Payments"
      ],
      "product": "PayID",
      "products": [
        "PayID"
      ]
    },
    {
      "id": "ID-31",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Addressing Model (PayID & Account Structure)",
      "category2": "Reconciliation, Reporting & Traceability",
      "journeyStage": "Receiving, validating, and reconciling (Employee's Super Fund)",
      "title": "Register a dedicated PayID to each employee (e.g. allocated member #) which could follow the employee. Need to consider the processes around this and the superstream governance around it",
      "problemScenario": "",
      "issueType": "Gap",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayID",
      "productsImpacted": "PayTo",
      "owner": "Bianca",
      "priority": "LOW",
      "horizon": "LONG",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "Decisions pending.",
      "notes": "",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "PayID",
      "products": [
        "PayID",
        "PayTo"
      ]
    },
    {
      "id": "ID-32",
      "mainUseCase": "Super",
      "useCasesImpacted": "Government",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "Addressing Model (PayID & Account Structure)",
      "journeyStage": "",
      "title": "Guidance have been recommended as opposed to mandatory - PayID usage for super - Proposed PayTo agreement - PRN for SCT payments is a should",
      "problemScenario": "Across the ecosystem, key practices such as PayID usage, PayTo agreements and PRN handling are recommended but not enforced as mandatory standards. This results in inconsistent adoption and fragmented implementation across participants. Currently, reliance on guidance rather than mandates leads to variability in how solutions are implemented. There is a need to assess where mandatory standards are required to drive consistency and interoperability.",
      "issueType": "Opportunity",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Other",
      "productsImpacted": "SCT",
      "owner": "TBD",
      "priority": "TBD",
      "horizon": "TBD",
      "status": "ACKNOWLEDGE",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "Note: We can't enforce this as we can't identify a payment as super under SCT. However our rules ensure that the end to end ID is passed on to Payee.",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Government"
      ],
      "product": "Other",
      "products": [
        "Other",
        "SCT"
      ]
    },
    {
      "id": "ID-33",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Payment instruction and Operation",
      "category2": "Reconciliation, Reporting & Traceability",
      "journeyStage": "Allocation and distribution (SuperStream)",
      "title": "Payment instruction should include fields for PayID, PayTo + CoP outcomes",
      "problemScenario": "",
      "issueType": "Risk",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Payment Instruction",
      "productsImpacted": "Reporting",
      "owner": "Bianca",
      "priority": "MEDIUM",
      "horizon": "LONG",
      "status": "WIP",
      "currentAction": "Makes reports action-oriented instead of note-oriented",
      "decisionNeeded": "",
      "notes": "Was being incorporated in the standard payment instruction Review of payment instructions were had",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "Payment Instruction",
      "products": [
        "Payment Instruction",
        "Reporting"
      ]
    },
    {
      "id": "ID-34",
      "mainUseCase": "Super",
      "useCasesImpacted": "All",
      "category": "Payment instruction and Operation",
      "category2": "",
      "journeyStage": "Payment processing",
      "title": "Bulk payment instruction capabilities - For the super use case: refunds from super funds and employer direct to super fund payments (channel B)",
      "problemScenario": "",
      "issueType": "Product Idea",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Payment Instruction",
      "productsImpacted": "Other",
      "owner": "Bianca",
      "priority": "MEDIUM",
      "horizon": "MEDIUM",
      "status": "WIP",
      "currentAction": "Makes reports action-oriented instead of note-oriented",
      "decisionNeeded": "",
      "notes": "Enablement: Working with DSPs (SAP) to enable bulk payment instruction.",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "All"
      ],
      "product": "Payment Instruction",
      "products": [
        "Payment Instruction",
        "Other"
      ]
    },
    {
      "id": "ID-35",
      "mainUseCase": "Super",
      "useCasesImpacted": "Business Payments",
      "category": "Standardisation & Interoperability",
      "category2": "",
      "journeyStage": "Preparation and data creation",
      "title": "Lack of Standardisation of payment instruction makes it difficult for DSP to adopt",
      "problemScenario": "",
      "issueType": "PE",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Payment Instruction",
      "productsImpacted": "Accounts",
      "owner": "Bianca",
      "priority": "MEDIUM",
      "horizon": "LONG",
      "status": "WIP",
      "currentAction": "Makes reports action-oriented instead of note-oriented",
      "decisionNeeded": "",
      "notes": "Work on a standard payment instruction is ongoing however is dependent on the A2A vision and roadmap",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Business Payments"
      ],
      "product": "Payment Instruction",
      "products": [
        "Payment Instruction",
        "Accounts"
      ]
    },
    {
      "id": "ID-36",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Payment instruction and Operation",
      "category2": "",
      "journeyStage": "Contribution data &payment method definition",
      "title": "Differences in the mechanism for PayTo (Request to push the payment out) vs Direct Debit (Pull)",
      "problemScenario": "",
      "issueType": "Dependency",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayTo",
      "productsImpacted": "CATSCT",
      "owner": "TBD",
      "priority": "TBD",
      "horizon": "TBD",
      "status": "ACKNOWLEDGE",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "PayTo",
      "products": [
        "PayTo",
        "CATSCT"
      ]
    },
    {
      "id": "ID-37",
      "mainUseCase": "Super",
      "useCasesImpacted": "Government",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "",
      "journeyStage": "Set up & Account",
      "title": "PayTo service variability - including whether PayTo initiator is being offered",
      "problemScenario": "",
      "issueType": "Gap",
      "dependencies": "ID-38; ID-42",
      "relatedInitiative": "",
      "primaryProduct": "PayTo",
      "productsImpacted": "CoP",
      "owner": "Colleen",
      "priority": "MEDIUM",
      "horizon": "MEDIUM",
      "status": "WIP",
      "currentAction": "Makes reports action-oriented instead of note-oriented",
      "decisionNeeded": "",
      "notes": "Working on the March Service Variability report",
      "link1": "Payments via PayTo availability - Move to NPP (MTN) Program Squad - Confluence",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Government"
      ],
      "product": "PayTo",
      "products": [
        "PayTo",
        "CoP"
      ]
    },
    {
      "id": "ID-38",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Payment Setup & Configuration",
      "category2": "",
      "journeyStage": "Set up & Account",
      "title": "PayTo limits are too low for what is required for super",
      "problemScenario": "",
      "issueType": "Opportunity",
      "dependencies": "ID-37",
      "relatedInitiative": "",
      "primaryProduct": "PayTo",
      "productsImpacted": "Osko",
      "owner": "Colleen",
      "priority": "HIGH",
      "horizon": "MEDIUM",
      "status": "WIP",
      "currentAction": "Makes reports action-oriented instead of note-oriented",
      "decisionNeeded": "",
      "notes": "Enablement/PayTo: Working on a Super PayTo agreement proposal",
      "link1": "PayTo Limits - Move to NPP (MTN) Program Squad - Confluence",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "PayTo",
      "products": [
        "PayTo",
        "Osko"
      ]
    },
    {
      "id": "ID-39",
      "mainUseCase": "Super",
      "useCasesImpacted": "All",
      "category": "Payment Setup & Configuration",
      "category2": "",
      "journeyStage": "Set up & Account",
      "title": "The population of ultimate creditor for super",
      "problemScenario": "",
      "issueType": "Risk",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayTo",
      "productsImpacted": "PayID",
      "owner": "Colleen",
      "priority": "MEDIUM",
      "horizon": "SHORT",
      "status": "WIP",
      "currentAction": "Makes reports action-oriented instead of note-oriented",
      "decisionNeeded": "",
      "notes": "Enablement/PayTo: Working on a Super PayTo agreement proposal",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "All"
      ],
      "product": "PayTo",
      "products": [
        "PayTo",
        "PayID"
      ]
    },
    {
      "id": "ID-40",
      "mainUseCase": "Super",
      "useCasesImpacted": "Business Payments",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "",
      "journeyStage": "Payment processing",
      "title": "Understanding the implications and education around employer fast fail impact in comparison to high care experiences with direct debits (e.g. in cases there's insuffficient funds etc). Today they allow overrides",
      "problemScenario": "",
      "issueType": "Product Idea",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayTo",
      "productsImpacted": "PayTo",
      "owner": "Bianca",
      "priority": "MEDIUM",
      "horizon": "MEDIUM",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Business Payments"
      ],
      "product": "PayTo",
      "products": [
        "PayTo"
      ]
    },
    {
      "id": "ID-41",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "",
      "journeyStage": "Payment processing",
      "title": "PayTo liability impact and implications to the ecosystem",
      "problemScenario": "As PayTo is adopted within the super payment ecosystem, the liability model and implications of fraud-related holds are not clearly defined. This creates uncertainty for participants and introduces operational and risk management challenges. Currently, there is limited clarity on how liability is distributed across parties in fraud scenarios. There is a need to establish clear scheme-level rules and guidance on liability and fraud handling to ensure consistency and confidence across the ecosystem.",
      "issueType": "PE",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayTo",
      "productsImpacted": "SCT",
      "owner": "Colleen",
      "priority": "HIGH",
      "horizon": "MEDIUM",
      "status": "WIP",
      "currentAction": "Makes reports action-oriented instead of note-oriented",
      "decisionNeeded": "",
      "notes": "Continued work on liability and claim process",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "PayTo",
      "products": [
        "PayTo",
        "SCT"
      ]
    },
    {
      "id": "ID-42",
      "mainUseCase": "Super",
      "useCasesImpacted": "Government",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "",
      "journeyStage": "Contribution data &payment method definition",
      "title": "Implications of PayTo fraud holds",
      "problemScenario": "",
      "issueType": "Dependency",
      "dependencies": "ID-38",
      "relatedInitiative": "",
      "primaryProduct": "PayTo",
      "productsImpacted": "Reporting",
      "owner": "Colleen",
      "priority": "MEDIUM",
      "horizon": "MEDIUM",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "With the PayTo Super agreement, further discussions about what it means when we get to the payment",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Government"
      ],
      "product": "PayTo",
      "products": [
        "PayTo",
        "Reporting"
      ]
    },
    {
      "id": "ID-43",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Payment Setup & Configuration",
      "category2": "",
      "journeyStage": "Set up & Account",
      "title": "PayTo mandate approval mechanism",
      "problemScenario": "",
      "issueType": "Gap",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayTo",
      "productsImpacted": "Other",
      "owner": "Colleen",
      "priority": "MEDIUM",
      "horizon": "SHORT",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "This is not just affecting super but other implementation e.g. Xero. Understand the processes around who is approving and how it works in practice in a business context Next Steps: Enablement can work through the thinking of the processes and recommendations",
      "link1": "PayTo approval process for businesses - Move to NPP (MTN) Program Squad - Confluence",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "PayTo",
      "products": [
        "PayTo",
        "Other"
      ]
    },
    {
      "id": "ID-44",
      "mainUseCase": "Super",
      "useCasesImpacted": "All",
      "category": "Standardisation & Interoperability",
      "category2": "",
      "journeyStage": "Contribution data &payment method definition",
      "title": "Lack of standardised PayTo APIs makes it difficult for ERPs to adopt (e.g. SAP)",
      "problemScenario": "",
      "issueType": "Opportunity",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "PayTo",
      "productsImpacted": "Accounts",
      "owner": "Colleen",
      "priority": "MEDIUM",
      "horizon": "LONG",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "All"
      ],
      "product": "PayTo",
      "products": [
        "PayTo",
        "Accounts"
      ]
    },
    {
      "id": "ID-45",
      "mainUseCase": "Super",
      "useCasesImpacted": "Business Payments",
      "category": "Reconciliation, Reporting & Traceability",
      "category2": "",
      "journeyStage": "Allocation and distribution (SuperStream)",
      "title": "Understanding the population of the PRN within the reporting",
      "problemScenario": "",
      "issueType": "Risk",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Reporting",
      "productsImpacted": "CATSCT",
      "owner": "Bianca",
      "priority": "HIGH",
      "horizon": "SHORT",
      "status": "WIP",
      "currentAction": "Makes reports action-oriented instead of note-oriented",
      "decisionNeeded": "",
      "notes": "Analysing how the PRN is being populated",
      "link1": "PRN Reconciliation - Troubleshooting - Move to NPP (MTN) Program Squad - Confluence",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Business Payments"
      ],
      "product": "Reporting",
      "products": [
        "Reporting",
        "CATSCT"
      ]
    },
    {
      "id": "ID-46",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Exceptions, Returns & Error Handling",
      "category2": "Reconciliation, Reporting & Traceability",
      "journeyStage": "Investigation and returns (unhappy path)",
      "title": "To refund a payment, the super fund may not have enough information in their reporting to send the payment back (e.g. account/PayID)",
      "problemScenario": "",
      "issueType": "Product Idea",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Reporting",
      "productsImpacted": "Accounts",
      "owner": "Nick",
      "priority": "HIGH",
      "horizon": "MEDIUM",
      "status": "NOT STARTED",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "Discussions have been had about the Osko CX",
      "link1": "NPP for super contribution refunds - Move to NPP (MTN) Program Squad - Confluence",
      "link2": "PRN reporting and Enablers analysis and tracking.xlsx",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "Reporting",
      "products": [
        "Reporting",
        "Accounts"
      ]
    },
    {
      "id": "ID-47",
      "mainUseCase": "Super",
      "useCasesImpacted": "Government",
      "category": "Payment instruction and Operation",
      "category2": "Reconciliation, Reporting & Traceability",
      "journeyStage": "Receiving, validating, and reconciling (Employee's Super Fund)",
      "title": "PRN in payment instruction and contribution data does not match",
      "problemScenario": "",
      "issueType": "PE",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Reporting",
      "productsImpacted": "Accounts",
      "owner": "",
      "priority": "",
      "horizon": "",
      "status": "",
      "currentAction": "Makes reports action-oriented instead of note-oriented",
      "decisionNeeded": "Decisions pending.",
      "notes": "",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Government"
      ],
      "product": "Reporting",
      "products": [
        "Reporting",
        "Accounts"
      ]
    },
    {
      "id": "ID-48",
      "mainUseCase": "Super",
      "useCasesImpacted": "Payroll",
      "category": "Ecosystem Readiness & External Constraints",
      "category2": "",
      "journeyStage": "Receiving, validating, and reconciling (SuperStream)",
      "title": "Clearing house holds funds",
      "problemScenario": "In the current SuperStream model, clearing houses receive, hold and redistribute funds as part of processing contributions. This introduces delays, increases reconciliation complexity and creates inefficiencies in fund movement. Currently, funds may sit in clearing house accounts while files are sliced and diced. There is a need to move towards more direct and real-time payment models that remove the need for intermediary fund holding.",
      "issueType": "Dependency",
      "dependencies": "",
      "relatedInitiative": "",
      "primaryProduct": "Accounts",
      "productsImpacted": "Accounts",
      "owner": "TBD",
      "priority": "MEDIUM",
      "horizon": "LONG",
      "status": "ACKNOWLEDGE",
      "currentAction": "",
      "decisionNeeded": "",
      "notes": "",
      "link1": "",
      "link2": "",
      "lastUpdated": "2026-05-12",
      "execSummaryTag": "Yes",
      "isExecSummary": true,
      "useCase": "Super",
      "useCases": [
        "Super",
        "Payroll"
      ],
      "product": "Accounts",
      "products": [
        "Accounts"
      ]
    }
  ]
};
